services:
  mongodb:
    container_name: mongodb-todo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    environment:
      - NAME=todo-mongodb
volumes:
  mongodb: